apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "jiralert.fullname" . }}-config
  namespace: {{ .Values.namespace }}
stringData:
  jiralert.tmpl: |
{{ .Values.jiratemplate | indent 4 }}
  jiralert.yml: |
{{ .Values.jirayml | indent 4 }}
