apiVersion: v1
kind: Service
metadata:
  name: {{ include "jiralert.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.names.deploylabel }}
  ports:
  - port: 9097
    targetPort: 9097
